//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTR
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ProductosCollection", Namespace="http://tempuri.org/", ItemName="producto")]
    public class ProductosCollection : System.Collections.Generic.List<ServiceTR.ProductoResponse>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoResponse", Namespace="http://tempuri.org/")]
    public partial class ProductoResponse : object
    {
        
        private string codigoProductoField;
        
        private string descripcionProductoField;
        
        private string empresaProductoField;
        
        private int tipoProductoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string codigoProducto
        {
            get
            {
                return this.codigoProductoField;
            }
            set
            {
                this.codigoProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string descripcionProducto
        {
            get
            {
                return this.descripcionProductoField;
            }
            set
            {
                this.descripcionProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string empresaProducto
        {
            get
            {
                return this.empresaProductoField;
            }
            set
            {
                this.empresaProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int tipoProducto
        {
            get
            {
                return this.tipoProductoField;
            }
            set
            {
                this.tipoProductoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TransaccionesCollection", Namespace="http://tempuri.org/", ItemName="transaccion")]
    public class TransaccionesCollection : System.Collections.Generic.List<ServiceTR.TransaccionResponse>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransaccionResponse", Namespace="http://tempuri.org/")]
    public partial class TransaccionResponse : object
    {
        
        private string descripcionProductoField;
        
        private decimal montoField;
        
        private string datosField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string descripcionProducto
        {
            get
            {
                return this.descripcionProductoField;
            }
            set
            {
                this.descripcionProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal monto
        {
            get
            {
                return this.montoField;
            }
            set
            {
                this.montoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string datos
        {
            get
            {
                return this.datosField;
            }
            set
            {
                this.datosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="EmpresasCobroCollection", Namespace="http://tempuri.org/", ItemName="empresaCobro")]
    public class EmpresasCobroCollection : System.Collections.Generic.List<ServiceTR.EmpresaCobroResponse>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaCobroResponse", Namespace="http://tempuri.org/")]
    public partial class EmpresaCobroResponse : object
    {
        
        private string codigoField;
        
        private string descripcionField;
        
        private string rubroField;
        
        private string monedaField;
        
        private bool aceptaPagoVoluntarioField;
        
        private bool aceptaPagoFacturaField;
        
        private bool aceptaModificacionImporteField;
        
        private string descripcionIdentificadorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string rubro
        {
            get
            {
                return this.rubroField;
            }
            set
            {
                this.rubroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string moneda
        {
            get
            {
                return this.monedaField;
            }
            set
            {
                this.monedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool aceptaPagoVoluntario
        {
            get
            {
                return this.aceptaPagoVoluntarioField;
            }
            set
            {
                this.aceptaPagoVoluntarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool aceptaPagoFactura
        {
            get
            {
                return this.aceptaPagoFacturaField;
            }
            set
            {
                this.aceptaPagoFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool aceptaModificacionImporte
        {
            get
            {
                return this.aceptaModificacionImporteField;
            }
            set
            {
                this.aceptaModificacionImporteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public string descripcionIdentificador
        {
            get
            {
                return this.descripcionIdentificadorField;
            }
            set
            {
                this.descripcionIdentificadorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CobrosEmpresaCollection", Namespace="http://tempuri.org/", ItemName="cobroEmpresa")]
    public class CobrosEmpresaCollection : System.Collections.Generic.List<ServiceTR.CobroEmpresaResponse>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CobroEmpresaResponse", Namespace="http://tempuri.org/")]
    public partial class CobroEmpresaResponse : object
    {
        
        private string codigoEmpresaField;
        
        private string descripcionEmpresaField;
        
        private string monedaField;
        
        private string clienteField;
        
        private string codigoBarrasField;
        
        private string descripcionField;
        
        private string facturaField;
        
        private string vencimientoField;
        
        private string detallesField;
        
        private string titulosDetallesField;
        
        private int importeField;
        
        private string datosExternosField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string codigoEmpresa
        {
            get
            {
                return this.codigoEmpresaField;
            }
            set
            {
                this.codigoEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string descripcionEmpresa
        {
            get
            {
                return this.descripcionEmpresaField;
            }
            set
            {
                this.descripcionEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string moneda
        {
            get
            {
                return this.monedaField;
            }
            set
            {
                this.monedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string cliente
        {
            get
            {
                return this.clienteField;
            }
            set
            {
                this.clienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string codigoBarras
        {
            get
            {
                return this.codigoBarrasField;
            }
            set
            {
                this.codigoBarrasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string factura
        {
            get
            {
                return this.facturaField;
            }
            set
            {
                this.facturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public string vencimiento
        {
            get
            {
                return this.vencimientoField;
            }
            set
            {
                this.vencimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=8)]
        public string detalles
        {
            get
            {
                return this.detallesField;
            }
            set
            {
                this.detallesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=9)]
        public string titulosDetalles
        {
            get
            {
                return this.titulosDetallesField;
            }
            set
            {
                this.titulosDetallesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int importe
        {
            get
            {
                return this.importeField;
            }
            set
            {
                this.importeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=11)]
        public string datosExternos
        {
            get
            {
                return this.datosExternosField;
            }
            set
            {
                this.datosExternosField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTR.IpsGvWebServiceSoap")]
    public interface IpsGvWebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VentaRecarga", ReplyAction="*")]
        ServiceTR.consultaRecargaResponse ventaRecarga(ServiceTR.ventaRecargaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VentaRecarga", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTR.consultaRecargaResponse> ventaRecargaAsync(ServiceTR.ventaRecargaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VentaPines", ReplyAction="*")]
        ServiceTR.ventaPinesResponse ventaPines(ServiceTR.ventaPinesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VentaPines", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTR.ventaPinesResponse> ventaPinesAsync(ServiceTR.ventaPinesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstadoVenta", ReplyAction="*")]
        ServiceTR.estadoVentaResponse estadoVenta(ServiceTR.estadoVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstadoVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTR.estadoVentaResponse> estadoVentaAsync(ServiceTR.estadoVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaSaldo", ReplyAction="*")]
        ServiceTR.consultaSaldoResponse consultaSaldo(ServiceTR.consultaSaldoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaSaldo", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTR.consultaSaldoResponse> consultaSaldoAsync(ServiceTR.consultaSaldoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaProductos", ReplyAction="*")]
        ServiceTR.consultaProductosResponse consultaProductos(ServiceTR.consultaProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTR.consultaProductosResponse> consultaProductosAsync(ServiceTR.consultaProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaVentas", ReplyAction="*")]
        ServiceTR.consultaVentasResponse consultaVentas(ServiceTR.consultaVentasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaVentas", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTR.consultaVentasResponse> consultaVentasAsync(ServiceTR.consultaVentasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaPendientes", ReplyAction="*")]
        ServiceTR.consultaPendientesResponse consultaPendientes(ServiceTR.consultaPendientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaPendientes", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTR.consultaPendientesResponse> consultaPendientesAsync(ServiceTR.consultaPendientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SolicitudSaldo", ReplyAction="*")]
        ServiceTR.solicitudSaldoResponse solicitudSaldo(ServiceTR.solicitudSaldoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SolicitudSaldo", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTR.solicitudSaldoResponse> solicitudSaldoAsync(ServiceTR.solicitudSaldoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaEmpresasCobro", ReplyAction="*")]
        ServiceTR.consultaEmpresasCobroResponse consultaEmpresasCobro(ServiceTR.consultaEmpresasCobroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaEmpresasCobro", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTR.consultaEmpresasCobroResponse> consultaEmpresasCobroAsync(ServiceTR.consultaEmpresasCobroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaCobrosPorEmpresa", ReplyAction="*")]
        ServiceTR.consultaCobrosPorEmpresaResponse consultaCobrosPorEmpresa(ServiceTR.consultaCobrosPorEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaCobrosPorEmpresa", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTR.consultaCobrosPorEmpresaResponse> consultaCobrosPorEmpresaAsync(ServiceTR.consultaCobrosPorEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaCobrosPorCB", ReplyAction="*")]
        ServiceTR.consultaCobrosPorCBResponse consultaCobrosPorCB(ServiceTR.consultaCobrosPorCBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaCobrosPorCB", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTR.consultaCobrosPorCBResponse> consultaCobrosPorCBAsync(ServiceTR.consultaCobrosPorCBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CobroFactura", ReplyAction="*")]
        ServiceTR.cobroFacturaResponse cobroFactura(ServiceTR.cobroFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CobroFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTR.cobroFacturaResponse> cobroFacturaAsync(ServiceTR.cobroFacturaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ventaRecargaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VentaRecargaRequest", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.ventaRecargaRequestBody Body;
        
        public ventaRecargaRequest()
        {
        }
        
        public ventaRecargaRequest(ServiceTR.ventaRecargaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ventaRecargaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nroTransaccionExt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string terminalNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string terminalType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int producto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string prefijoPais;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string codigoArea;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string numeroTelefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string datosRecarga;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public int importe;
        
        public ventaRecargaRequestBody()
        {
        }
        
        public ventaRecargaRequestBody(string usuario, string password, int cliente, int cuenta, string nroTransaccionExt, string terminalNumber, string terminalType, int producto, string prefijoPais, string codigoArea, string numeroTelefono, string datosRecarga, int importe)
        {
            this.usuario = usuario;
            this.password = password;
            this.cliente = cliente;
            this.cuenta = cuenta;
            this.nroTransaccionExt = nroTransaccionExt;
            this.terminalNumber = terminalNumber;
            this.terminalType = terminalType;
            this.producto = producto;
            this.prefijoPais = prefijoPais;
            this.codigoArea = codigoArea;
            this.numeroTelefono = numeroTelefono;
            this.datosRecarga = datosRecarga;
            this.importe = importe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaRecargaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VentaRecargaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.ventaRecargaResponseBody Body;
        
        public consultaRecargaResponse()
        {
        }
        
        public consultaRecargaResponse(ServiceTR.ventaRecargaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ventaRecargaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int respuesta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nroTransaccionProveedor;
        
        public ventaRecargaResponseBody()
        {
        }
        
        public ventaRecargaResponseBody(int respuesta, string mensaje, string nroTransaccionProveedor)
        {
            this.respuesta = respuesta;
            this.mensaje = mensaje;
            this.nroTransaccionProveedor = nroTransaccionProveedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ventaPinesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VentaPinesRequest", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.ventaPinesRequestBody Body;
        
        public ventaPinesRequest()
        {
        }
        
        public ventaPinesRequest(ServiceTR.ventaPinesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ventaPinesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string terminalNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string terminalType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string nroTransaccionExt;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int producto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string prefijoPais;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string codigoArea;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string numeroTelefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string datosRecarga;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public int importe;
        
        public ventaPinesRequestBody()
        {
        }
        
        public ventaPinesRequestBody(string usuario, string password, int cliente, int cuenta, string terminalNumber, string terminalType, string nroTransaccionExt, int producto, string prefijoPais, string codigoArea, string numeroTelefono, string datosRecarga, int importe)
        {
            this.usuario = usuario;
            this.password = password;
            this.cliente = cliente;
            this.cuenta = cuenta;
            this.terminalNumber = terminalNumber;
            this.terminalType = terminalType;
            this.nroTransaccionExt = nroTransaccionExt;
            this.producto = producto;
            this.prefijoPais = prefijoPais;
            this.codigoArea = codigoArea;
            this.numeroTelefono = numeroTelefono;
            this.datosRecarga = datosRecarga;
            this.importe = importe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ventaPinesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VentaPinesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.ventaPinesResponseBody Body;
        
        public ventaPinesResponse()
        {
        }
        
        public ventaPinesResponse(ServiceTR.ventaPinesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ventaPinesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int respuesta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nroTransaccionProveedor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nroPin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nroSeriePin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string vencimientoPin;
        
        public ventaPinesResponseBody()
        {
        }
        
        public ventaPinesResponseBody(int respuesta, string mensaje, string nroTransaccionProveedor, string nroPin, string nroSeriePin, string vencimientoPin)
        {
            this.respuesta = respuesta;
            this.mensaje = mensaje;
            this.nroTransaccionProveedor = nroTransaccionProveedor;
            this.nroPin = nroPin;
            this.nroSeriePin = nroSeriePin;
            this.vencimientoPin = vencimientoPin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class estadoVentaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EstadoVentaRequest", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.estadoVentaRequestBody Body;
        
        public estadoVentaRequest()
        {
        }
        
        public estadoVentaRequest(ServiceTR.estadoVentaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class estadoVentaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string terminalNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string terminalType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string nroTransaccionExt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string prefijoPais;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string codigoArea;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string numeroTelefono;
        
        public estadoVentaRequestBody()
        {
        }
        
        public estadoVentaRequestBody(string usuario, string password, int cliente, int cuenta, string terminalNumber, string terminalType, string nroTransaccionExt, string prefijoPais, string codigoArea, string numeroTelefono)
        {
            this.usuario = usuario;
            this.password = password;
            this.cliente = cliente;
            this.cuenta = cuenta;
            this.terminalNumber = terminalNumber;
            this.terminalType = terminalType;
            this.nroTransaccionExt = nroTransaccionExt;
            this.prefijoPais = prefijoPais;
            this.codigoArea = codigoArea;
            this.numeroTelefono = numeroTelefono;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class estadoVentaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EstadoVentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.estadoVentaResponseBody Body;
        
        public estadoVentaResponse()
        {
        }
        
        public estadoVentaResponse(ServiceTR.estadoVentaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class estadoVentaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int respuesta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nroTransaccionProveedor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nroPin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string nroSeriePin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string vencimientoPin;
        
        public estadoVentaResponseBody()
        {
        }
        
        public estadoVentaResponseBody(int respuesta, string mensaje, string nroTransaccionProveedor, string ticket, string nroPin, string nroSeriePin, string vencimientoPin)
        {
            this.respuesta = respuesta;
            this.mensaje = mensaje;
            this.nroTransaccionProveedor = nroTransaccionProveedor;
            this.ticket = ticket;
            this.nroPin = nroPin;
            this.nroSeriePin = nroSeriePin;
            this.vencimientoPin = vencimientoPin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaSaldoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaSaldoRequest", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.consultaSaldoRequestBody Body;
        
        public consultaSaldoRequest()
        {
        }
        
        public consultaSaldoRequest(ServiceTR.consultaSaldoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaSaldoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string terminalNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string terminalType;
        
        public consultaSaldoRequestBody()
        {
        }
        
        public consultaSaldoRequestBody(string usuario, string password, int cliente, int cuenta, string terminalNumber, string terminalType)
        {
            this.usuario = usuario;
            this.password = password;
            this.cliente = cliente;
            this.cuenta = cuenta;
            this.terminalNumber = terminalNumber;
            this.terminalType = terminalType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaSaldoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaSaldoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.consultaSaldoResponseBody Body;
        
        public consultaSaldoResponse()
        {
        }
        
        public consultaSaldoResponse(ServiceTR.consultaSaldoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaSaldoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int respuesta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int saldo;
        
        public consultaSaldoResponseBody()
        {
        }
        
        public consultaSaldoResponseBody(int respuesta, string mensaje, int saldo)
        {
            this.respuesta = respuesta;
            this.mensaje = mensaje;
            this.saldo = saldo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaProductosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaProductosRequest", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.consultaProductosRequestBody Body;
        
        public consultaProductosRequest()
        {
        }
        
        public consultaProductosRequest(ServiceTR.consultaProductosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaProductosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string terminalNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string terminalType;
        
        public consultaProductosRequestBody()
        {
        }
        
        public consultaProductosRequestBody(string usuario, string password, int cliente, int cuenta, string terminalNumber, string terminalType)
        {
            this.usuario = usuario;
            this.password = password;
            this.cliente = cliente;
            this.cuenta = cuenta;
            this.terminalNumber = terminalNumber;
            this.terminalType = terminalType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaProductosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaProductosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.consultaProductosResponseBody Body;
        
        public consultaProductosResponse()
        {
        }
        
        public consultaProductosResponse(ServiceTR.consultaProductosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaProductosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int respuesta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ServiceTR.ProductosCollection productos;
        
        public consultaProductosResponseBody()
        {
        }
        
        public consultaProductosResponseBody(int respuesta, string mensaje, ServiceTR.ProductosCollection productos)
        {
            this.respuesta = respuesta;
            this.mensaje = mensaje;
            this.productos = productos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaVentasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaVentasRequest", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.consultaVentasRequestBody Body;
        
        public consultaVentasRequest()
        {
        }
        
        public consultaVentasRequest(ServiceTR.consultaVentasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaVentasRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string terminalNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string terminalType;
        
        public consultaVentasRequestBody()
        {
        }
        
        public consultaVentasRequestBody(string usuario, string password, int cliente, int cuenta, string terminalNumber, string terminalType)
        {
            this.usuario = usuario;
            this.password = password;
            this.cliente = cliente;
            this.cuenta = cuenta;
            this.terminalNumber = terminalNumber;
            this.terminalType = terminalType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaVentasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaVentasResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.consultaVentasResponseBody Body;
        
        public consultaVentasResponse()
        {
        }
        
        public consultaVentasResponse(ServiceTR.consultaVentasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaVentasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int respuesta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ServiceTR.TransaccionesCollection transacciones;
        
        public consultaVentasResponseBody()
        {
        }
        
        public consultaVentasResponseBody(int respuesta, string mensaje, ServiceTR.TransaccionesCollection transacciones)
        {
            this.respuesta = respuesta;
            this.mensaje = mensaje;
            this.transacciones = transacciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaPendientesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaPendientesRequest", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.consultaPendientesRequestBody Body;
        
        public consultaPendientesRequest()
        {
        }
        
        public consultaPendientesRequest(ServiceTR.consultaPendientesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaPendientesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string terminalNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string terminalType;
        
        public consultaPendientesRequestBody()
        {
        }
        
        public consultaPendientesRequestBody(string usuario, string password, int cliente, int cuenta, string terminalNumber, string terminalType)
        {
            this.usuario = usuario;
            this.password = password;
            this.cliente = cliente;
            this.cuenta = cuenta;
            this.terminalNumber = terminalNumber;
            this.terminalType = terminalType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaPendientesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaPendientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.consultaPendientesResponseBody Body;
        
        public consultaPendientesResponse()
        {
        }
        
        public consultaPendientesResponse(ServiceTR.consultaPendientesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaPendientesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int respuesta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ServiceTR.TransaccionesCollection transacciones;
        
        public consultaPendientesResponseBody()
        {
        }
        
        public consultaPendientesResponseBody(int respuesta, string mensaje, ServiceTR.TransaccionesCollection transacciones)
        {
            this.respuesta = respuesta;
            this.mensaje = mensaje;
            this.transacciones = transacciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitudSaldoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SolicitudSaldoRequest", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.solicitudSaldoRequestBody Body;
        
        public solicitudSaldoRequest()
        {
        }
        
        public solicitudSaldoRequest(ServiceTR.solicitudSaldoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class solicitudSaldoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nroTransaccionExt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string terminalNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string terminalType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int producto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int importe;
        
        public solicitudSaldoRequestBody()
        {
        }
        
        public solicitudSaldoRequestBody(string usuario, string password, int cliente, int cuenta, string nroTransaccionExt, string terminalNumber, string terminalType, int producto, int importe)
        {
            this.usuario = usuario;
            this.password = password;
            this.cliente = cliente;
            this.cuenta = cuenta;
            this.nroTransaccionExt = nroTransaccionExt;
            this.terminalNumber = terminalNumber;
            this.terminalType = terminalType;
            this.producto = producto;
            this.importe = importe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitudSaldoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SolicitudSaldoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.solicitudSaldoResponseBody Body;
        
        public solicitudSaldoResponse()
        {
        }
        
        public solicitudSaldoResponse(ServiceTR.solicitudSaldoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class solicitudSaldoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int respuesta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nroTransaccionProveedor;
        
        public solicitudSaldoResponseBody()
        {
        }
        
        public solicitudSaldoResponseBody(int respuesta, string mensaje, string nroTransaccionProveedor)
        {
            this.respuesta = respuesta;
            this.mensaje = mensaje;
            this.nroTransaccionProveedor = nroTransaccionProveedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaEmpresasCobroRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaEmpresasCobroRequest", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.consultaEmpresasCobroRequestBody Body;
        
        public consultaEmpresasCobroRequest()
        {
        }
        
        public consultaEmpresasCobroRequest(ServiceTR.consultaEmpresasCobroRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaEmpresasCobroRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string terminalNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string terminalType;
        
        public consultaEmpresasCobroRequestBody()
        {
        }
        
        public consultaEmpresasCobroRequestBody(string usuario, string password, int cliente, int cuenta, string terminalNumber, string terminalType)
        {
            this.usuario = usuario;
            this.password = password;
            this.cliente = cliente;
            this.cuenta = cuenta;
            this.terminalNumber = terminalNumber;
            this.terminalType = terminalType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaEmpresasCobroResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaEmpresasCobroResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.consultaEmpresasCobroResponseBody Body;
        
        public consultaEmpresasCobroResponse()
        {
        }
        
        public consultaEmpresasCobroResponse(ServiceTR.consultaEmpresasCobroResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaEmpresasCobroResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int respuesta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ServiceTR.EmpresasCobroCollection empresas;
        
        public consultaEmpresasCobroResponseBody()
        {
        }
        
        public consultaEmpresasCobroResponseBody(int respuesta, string mensaje, ServiceTR.EmpresasCobroCollection empresas)
        {
            this.respuesta = respuesta;
            this.mensaje = mensaje;
            this.empresas = empresas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCobrosPorEmpresaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaCobrosPorEmpresaRequest", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.consultaCobrosPorEmpresaRequestBody Body;
        
        public consultaCobrosPorEmpresaRequest()
        {
        }
        
        public consultaCobrosPorEmpresaRequest(ServiceTR.consultaCobrosPorEmpresaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaCobrosPorEmpresaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string terminalNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string terminalType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string codigoEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string identificador;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int pagoVoluntario;
        
        public consultaCobrosPorEmpresaRequestBody()
        {
        }
        
        public consultaCobrosPorEmpresaRequestBody(string usuario, string password, int cliente, int cuenta, string terminalNumber, string terminalType, string codigoEmpresa, string identificador, int pagoVoluntario)
        {
            this.usuario = usuario;
            this.password = password;
            this.cliente = cliente;
            this.cuenta = cuenta;
            this.terminalNumber = terminalNumber;
            this.terminalType = terminalType;
            this.codigoEmpresa = codigoEmpresa;
            this.identificador = identificador;
            this.pagoVoluntario = pagoVoluntario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCobrosPorEmpresaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaCobrosPorEmpresaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.consultaCobrosPorEmpresaResponseBody Body;
        
        public consultaCobrosPorEmpresaResponse()
        {
        }
        
        public consultaCobrosPorEmpresaResponse(ServiceTR.consultaCobrosPorEmpresaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaCobrosPorEmpresaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int respuesta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ServiceTR.CobrosEmpresaCollection cobrosEmpresa;
        
        public consultaCobrosPorEmpresaResponseBody()
        {
        }
        
        public consultaCobrosPorEmpresaResponseBody(int respuesta, string mensaje, ServiceTR.CobrosEmpresaCollection cobrosEmpresa)
        {
            this.respuesta = respuesta;
            this.mensaje = mensaje;
            this.cobrosEmpresa = cobrosEmpresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCobrosPorCBRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaCobrosPorCBRequest", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.consultaCobrosPorCBRequestBody Body;
        
        public consultaCobrosPorCBRequest()
        {
        }
        
        public consultaCobrosPorCBRequest(ServiceTR.consultaCobrosPorCBRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaCobrosPorCBRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string terminalNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string terminalType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string codigoEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string codigoBarras;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int pagoVoluntario;
        
        public consultaCobrosPorCBRequestBody()
        {
        }
        
        public consultaCobrosPorCBRequestBody(string usuario, string password, int cliente, int cuenta, string terminalNumber, string terminalType, string codigoEmpresa, string codigoBarras, int pagoVoluntario)
        {
            this.usuario = usuario;
            this.password = password;
            this.cliente = cliente;
            this.cuenta = cuenta;
            this.terminalNumber = terminalNumber;
            this.terminalType = terminalType;
            this.codigoEmpresa = codigoEmpresa;
            this.codigoBarras = codigoBarras;
            this.pagoVoluntario = pagoVoluntario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCobrosPorCBResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaCobrosPorCBResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.consultaCobrosPorCBResponseBody Body;
        
        public consultaCobrosPorCBResponse()
        {
        }
        
        public consultaCobrosPorCBResponse(ServiceTR.consultaCobrosPorCBResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaCobrosPorCBResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int respuesta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ServiceTR.CobrosEmpresaCollection cobrosEmpresa;
        
        public consultaCobrosPorCBResponseBody()
        {
        }
        
        public consultaCobrosPorCBResponseBody(int respuesta, string mensaje, ServiceTR.CobrosEmpresaCollection cobrosEmpresa)
        {
            this.respuesta = respuesta;
            this.mensaje = mensaje;
            this.cobrosEmpresa = cobrosEmpresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cobroFacturaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CobroFacturaRequest", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.cobroFacturaRequestBody Body;
        
        public cobroFacturaRequest()
        {
        }
        
        public cobroFacturaRequest(ServiceTR.cobroFacturaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class cobroFacturaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string terminalNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string terminalType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string nroTransaccionExt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public ServiceTR.CobroEmpresaResponse cobroEmpresa;
        
        public cobroFacturaRequestBody()
        {
        }
        
        public cobroFacturaRequestBody(string usuario, string password, int cliente, int cuenta, string terminalNumber, string terminalType, string nroTransaccionExt, ServiceTR.CobroEmpresaResponse cobroEmpresa)
        {
            this.usuario = usuario;
            this.password = password;
            this.cliente = cliente;
            this.cuenta = cuenta;
            this.terminalNumber = terminalNumber;
            this.terminalType = terminalType;
            this.nroTransaccionExt = nroTransaccionExt;
            this.cobroEmpresa = cobroEmpresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cobroFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CobroFacturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTR.cobroFacturaResponseBody Body;
        
        public cobroFacturaResponse()
        {
        }
        
        public cobroFacturaResponse(ServiceTR.cobroFacturaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class cobroFacturaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int respuesta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ServiceTR.CobrosEmpresaCollection cobrosEmpresa;
        
        public cobroFacturaResponseBody()
        {
        }
        
        public cobroFacturaResponseBody(int respuesta, string mensaje, string ticket, ServiceTR.CobrosEmpresaCollection cobrosEmpresa)
        {
            this.respuesta = respuesta;
            this.mensaje = mensaje;
            this.ticket = ticket;
            this.cobrosEmpresa = cobrosEmpresa;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface IpsGvWebServiceSoapChannel : ServiceTR.IpsGvWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class IpsGvWebServiceSoapClient : System.ServiceModel.ClientBase<ServiceTR.IpsGvWebServiceSoap>, ServiceTR.IpsGvWebServiceSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IpsGvWebServiceSoapClient() : 
                base(IpsGvWebServiceSoapClient.GetDefaultBinding(), IpsGvWebServiceSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IpsGvWebServiceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IpsGvWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(IpsGvWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), IpsGvWebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IpsGvWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IpsGvWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IpsGvWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IpsGvWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IpsGvWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceTR.consultaRecargaResponse ventaRecarga(ServiceTR.ventaRecargaRequest request)
        {
            return base.Channel.ventaRecarga(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTR.consultaRecargaResponse> ventaRecargaAsync(ServiceTR.ventaRecargaRequest request)
        {
            return base.Channel.ventaRecargaAsync(request);
        }
        
        public ServiceTR.ventaPinesResponse ventaPines(ServiceTR.ventaPinesRequest request)
        {
            return base.Channel.ventaPines(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTR.ventaPinesResponse> ventaPinesAsync(ServiceTR.ventaPinesRequest request)
        {
            return base.Channel.ventaPinesAsync(request);
        }
        
        public ServiceTR.estadoVentaResponse estadoVenta(ServiceTR.estadoVentaRequest request)
        {
            return base.Channel.estadoVenta(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTR.estadoVentaResponse> estadoVentaAsync(ServiceTR.estadoVentaRequest request)
        {
            return base.Channel.estadoVentaAsync(request);
        }
        
        public ServiceTR.consultaSaldoResponse consultaSaldo(ServiceTR.consultaSaldoRequest request)
        {
            return base.Channel.consultaSaldo(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTR.consultaSaldoResponse> consultaSaldoAsync(ServiceTR.consultaSaldoRequest request)
        {
            return base.Channel.consultaSaldoAsync(request);
        }
        
        public ServiceTR.consultaProductosResponse consultaProductos(ServiceTR.consultaProductosRequest request)
        {
            return base.Channel.consultaProductos(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTR.consultaProductosResponse> consultaProductosAsync(ServiceTR.consultaProductosRequest request)
        {
            return base.Channel.consultaProductosAsync(request);
        }
        
        public ServiceTR.consultaVentasResponse consultaVentas(ServiceTR.consultaVentasRequest request)
        {
            return base.Channel.consultaVentas(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTR.consultaVentasResponse> consultaVentasAsync(ServiceTR.consultaVentasRequest request)
        {
            return base.Channel.consultaVentasAsync(request);
        }
        
        public ServiceTR.consultaPendientesResponse consultaPendientes(ServiceTR.consultaPendientesRequest request)
        {
            return base.Channel.consultaPendientes(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTR.consultaPendientesResponse> consultaPendientesAsync(ServiceTR.consultaPendientesRequest request)
        {
            return base.Channel.consultaPendientesAsync(request);
        }
        
        public ServiceTR.solicitudSaldoResponse solicitudSaldo(ServiceTR.solicitudSaldoRequest request)
        {
            return base.Channel.solicitudSaldo(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTR.solicitudSaldoResponse> solicitudSaldoAsync(ServiceTR.solicitudSaldoRequest request)
        {
            return base.Channel.solicitudSaldoAsync(request);
        }
        
        public ServiceTR.consultaEmpresasCobroResponse consultaEmpresasCobro(ServiceTR.consultaEmpresasCobroRequest request)
        {
            return base.Channel.consultaEmpresasCobro(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTR.consultaEmpresasCobroResponse> consultaEmpresasCobroAsync(ServiceTR.consultaEmpresasCobroRequest request)
        {
            return base.Channel.consultaEmpresasCobroAsync(request);
        }
        
        public ServiceTR.consultaCobrosPorEmpresaResponse consultaCobrosPorEmpresa(ServiceTR.consultaCobrosPorEmpresaRequest request)
        {
            return base.Channel.consultaCobrosPorEmpresa(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTR.consultaCobrosPorEmpresaResponse> consultaCobrosPorEmpresaAsync(ServiceTR.consultaCobrosPorEmpresaRequest request)
        {
            return base.Channel.consultaCobrosPorEmpresaAsync(request);
        }
        
        public ServiceTR.consultaCobrosPorCBResponse consultaCobrosPorCB(ServiceTR.consultaCobrosPorCBRequest request)
        {
            return base.Channel.consultaCobrosPorCB(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTR.consultaCobrosPorCBResponse> consultaCobrosPorCBAsync(ServiceTR.consultaCobrosPorCBRequest request)
        {
            return base.Channel.consultaCobrosPorCBAsync(request);
        }
        
        public ServiceTR.cobroFacturaResponse cobroFactura(ServiceTR.cobroFacturaRequest request)
        {
            return base.Channel.cobroFactura(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTR.cobroFacturaResponse> cobroFacturaAsync(ServiceTR.cobroFacturaRequest request)
        {
            return base.Channel.cobroFacturaAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IpsGvWebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IpsGvWebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://200.107.200.81:7238/SstWSServlet");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IpsGvWebServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.IpsGvWebServiceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IpsGvWebServiceSoapClient.GetEndpointAddress(EndpointConfiguration.IpsGvWebServiceSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            IpsGvWebServiceSoap,
        }
    }
}
