//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCE
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCE.IpwsCobranzaGlobal")]
    public interface IpwsCobranzaGlobal
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal#BuscarEmpresas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tRubros))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tBoletasACobrar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tValoresManuales))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tResultado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tIngresoManual))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tEmpresa))]
        ServiceCE.BuscarEmpresasResponse BuscarEmpresas(ServiceCE.BuscarEmpresasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal#BuscarEmpresas", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceCE.BuscarEmpresasResponse> BuscarEmpresasAsync(ServiceCE.BuscarEmpresasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal#BuscarResultados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tRubros))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tBoletasACobrar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tValoresManuales))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tResultado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tIngresoManual))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tEmpresa))]
        ServiceCE.BuscarResultadosResponse BuscarResultados(ServiceCE.BuscarResultadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal#BuscarResultados", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceCE.BuscarResultadosResponse> BuscarResultadosAsync(ServiceCE.BuscarResultadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal#ValidarDatos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tRubros))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tBoletasACobrar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tValoresManuales))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tResultado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tIngresoManual))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tEmpresa))]
        ServiceCE.ValidarDatosResponse ValidarDatos(ServiceCE.ValidarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal#ValidarDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceCE.ValidarDatosResponse> ValidarDatosAsync(ServiceCE.ValidarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal#BuscarRubros", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tRubros))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tBoletasACobrar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tValoresManuales))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tResultado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tIngresoManual))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tEmpresa))]
        ServiceCE.BuscarRubrosResponse BuscarRubros(ServiceCE.BuscarRubrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal#BuscarRubros", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceCE.BuscarRubrosResponse> BuscarRubrosAsync(ServiceCE.BuscarRubrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal#Monitor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tRubros))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tBoletasACobrar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tValoresManuales))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tResultado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tIngresoManual))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tEmpresa))]
        ServiceCE.MonitorResponse Monitor(ServiceCE.MonitorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal#Monitor", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceCE.MonitorResponse> MonitorAsync(ServiceCE.MonitorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal#Anulacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tRubros))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tBoletasACobrar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tValoresManuales))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tResultado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tIngresoManual))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tEmpresa))]
        ServiceCE.AnulacionResponse Anulacion(ServiceCE.AnulacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal#Anulacion", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceCE.AnulacionResponse> AnulacionAsync(ServiceCE.AnulacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal#AnulacionTimeOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tRubros))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tBoletasACobrar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tValoresManuales))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tResultado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tIngresoManual))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tEmpresa))]
        ServiceCE.AnulacionTimeOutResponse AnulacionTimeOut(ServiceCE.AnulacionTimeOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal#AnulacionTimeOut", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceCE.AnulacionTimeOutResponse> AnulacionTimeOutAsync(ServiceCE.AnulacionTimeOutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tParamBuscarEmpresas
    {
        
        private tEntidad entidadField;
        
        /// <remarks/>
        public tEntidad Entidad
        {
            get
            {
                return this.entidadField;
            }
            set
            {
                this.entidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tEntidad
    {
        
        private string usuarioField;
        
        private string claveField;
        
        /// <remarks/>
        public string Usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tParamAnulacionTimeOut
    {
        
        private tEntidad entidadField;
        
        private string motivoField;
        
        private string clientField;
        
        private string trnCliField;
        
        private int codEmpField;
        
        private string barraField;
        
        private double importField;
        
        /// <remarks/>
        public tEntidad Entidad
        {
            get
            {
                return this.entidadField;
            }
            set
            {
                this.entidadField = value;
            }
        }
        
        /// <remarks/>
        public string Motivo
        {
            get
            {
                return this.motivoField;
            }
            set
            {
                this.motivoField = value;
            }
        }
        
        /// <remarks/>
        public string Client
        {
            get
            {
                return this.clientField;
            }
            set
            {
                this.clientField = value;
            }
        }
        
        /// <remarks/>
        public string TrnCli
        {
            get
            {
                return this.trnCliField;
            }
            set
            {
                this.trnCliField = value;
            }
        }
        
        /// <remarks/>
        public int CodEmp
        {
            get
            {
                return this.codEmpField;
            }
            set
            {
                this.codEmpField = value;
            }
        }
        
        /// <remarks/>
        public string Barra
        {
            get
            {
                return this.barraField;
            }
            set
            {
                this.barraField = value;
            }
        }
        
        /// <remarks/>
        public double Import
        {
            get
            {
                return this.importField;
            }
            set
            {
                this.importField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tSalidaAnulacion
    {
        
        private tResultGral resultadoFuncionField;
        
        private string descriField;
        
        /// <remarks/>
        public tResultGral ResultadoFuncion
        {
            get
            {
                return this.resultadoFuncionField;
            }
            set
            {
                this.resultadoFuncionField = value;
            }
        }
        
        /// <remarks/>
        public string Descri
        {
            get
            {
                return this.descriField;
            }
            set
            {
                this.descriField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tResultGral
    {
        
        private int idField;
        
        /// <remarks/>
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tParamAnulacion
    {
        
        private tEntidad entidadField;
        
        private string motivoField;
        
        private string clientField;
        
        private string trnCliField;
        
        private int codEmpField;
        
        private int nroOpeField;
        
        private double importField;
        
        /// <remarks/>
        public tEntidad Entidad
        {
            get
            {
                return this.entidadField;
            }
            set
            {
                this.entidadField = value;
            }
        }
        
        /// <remarks/>
        public string Motivo
        {
            get
            {
                return this.motivoField;
            }
            set
            {
                this.motivoField = value;
            }
        }
        
        /// <remarks/>
        public string Client
        {
            get
            {
                return this.clientField;
            }
            set
            {
                this.clientField = value;
            }
        }
        
        /// <remarks/>
        public string TrnCli
        {
            get
            {
                return this.trnCliField;
            }
            set
            {
                this.trnCliField = value;
            }
        }
        
        /// <remarks/>
        public int CodEmp
        {
            get
            {
                return this.codEmpField;
            }
            set
            {
                this.codEmpField = value;
            }
        }
        
        /// <remarks/>
        public int NroOpe
        {
            get
            {
                return this.nroOpeField;
            }
            set
            {
                this.nroOpeField = value;
            }
        }
        
        /// <remarks/>
        public double Import
        {
            get
            {
                return this.importField;
            }
            set
            {
                this.importField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tRubros
    {
        
        private int codRubField;
        
        private string descriRubField;
        
        /// <remarks/>
        public int CodRub
        {
            get
            {
                return this.codRubField;
            }
            set
            {
                this.codRubField = value;
            }
        }
        
        /// <remarks/>
        public string DescriRub
        {
            get
            {
                return this.descriRubField;
            }
            set
            {
                this.descriRubField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tSalidaBuscarRubros
    {
        
        private tResultGral resultadoFuncionField;
        
        private tRubros[] rubrosField;
        
        /// <remarks/>
        public tResultGral ResultadoFuncion
        {
            get
            {
                return this.resultadoFuncionField;
            }
            set
            {
                this.resultadoFuncionField = value;
            }
        }
        
        /// <remarks/>
        public tRubros[] Rubros
        {
            get
            {
                return this.rubrosField;
            }
            set
            {
                this.rubrosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tParamBuscarRubros
    {
        
        private tEntidad entidadField;
        
        /// <remarks/>
        public tEntidad Entidad
        {
            get
            {
                return this.entidadField;
            }
            set
            {
                this.entidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tBoletasACobrar
    {
        
        private double importeField;
        
        private string codBarraField;
        
        private string textoMostrarField;
        
        private string hashField;
        
        /// <remarks/>
        public double Importe
        {
            get
            {
                return this.importeField;
            }
            set
            {
                this.importeField = value;
            }
        }
        
        /// <remarks/>
        public string CodBarra
        {
            get
            {
                return this.codBarraField;
            }
            set
            {
                this.codBarraField = value;
            }
        }
        
        /// <remarks/>
        public string TextoMostrar
        {
            get
            {
                return this.textoMostrarField;
            }
            set
            {
                this.textoMostrarField = value;
            }
        }
        
        /// <remarks/>
        public string Hash
        {
            get
            {
                return this.hashField;
            }
            set
            {
                this.hashField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tSalidaValidarDatos
    {
        
        private tResultGral resultadoFuncionField;
        
        private tBoletasACobrar[] boletasACobrarField;
        
        private string textoGralField;
        
        private string titulosField;
        
        /// <remarks/>
        public tResultGral ResultadoFuncion
        {
            get
            {
                return this.resultadoFuncionField;
            }
            set
            {
                this.resultadoFuncionField = value;
            }
        }
        
        /// <remarks/>
        public tBoletasACobrar[] BoletasACobrar
        {
            get
            {
                return this.boletasACobrarField;
            }
            set
            {
                this.boletasACobrarField = value;
            }
        }
        
        /// <remarks/>
        public string TextoGral
        {
            get
            {
                return this.textoGralField;
            }
            set
            {
                this.textoGralField = value;
            }
        }
        
        /// <remarks/>
        public string Titulos
        {
            get
            {
                return this.titulosField;
            }
            set
            {
                this.titulosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tValoresManuales
    {
        
        private int codIngresoField;
        
        private string datoField;
        
        /// <remarks/>
        public int CodIngreso
        {
            get
            {
                return this.codIngresoField;
            }
            set
            {
                this.codIngresoField = value;
            }
        }
        
        /// <remarks/>
        public string Dato
        {
            get
            {
                return this.datoField;
            }
            set
            {
                this.datoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tParamValidarDatos
    {
        
        private tEntidad entidadField;
        
        private int codEmpField;
        
        private string codBarraField;
        
        private string clientField;
        
        private tValoresManuales[] valoresIngManualField;
        
        /// <remarks/>
        public tEntidad Entidad
        {
            get
            {
                return this.entidadField;
            }
            set
            {
                this.entidadField = value;
            }
        }
        
        /// <remarks/>
        public int CodEmp
        {
            get
            {
                return this.codEmpField;
            }
            set
            {
                this.codEmpField = value;
            }
        }
        
        /// <remarks/>
        public string CodBarra
        {
            get
            {
                return this.codBarraField;
            }
            set
            {
                this.codBarraField = value;
            }
        }
        
        /// <remarks/>
        public string Client
        {
            get
            {
                return this.clientField;
            }
            set
            {
                this.clientField = value;
            }
        }
        
        /// <remarks/>
        public tValoresManuales[] ValoresIngManual
        {
            get
            {
                return this.valoresIngManualField;
            }
            set
            {
                this.valoresIngManualField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tResultado
    {
        
        private int idField;
        
        private string descriField;
        
        /// <remarks/>
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Descri
        {
            get
            {
                return this.descriField;
            }
            set
            {
                this.descriField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tSalidaBuscarResultados
    {
        
        private tResultGral resultadoFuncionField;
        
        private tResultado[] resultadoField;
        
        /// <remarks/>
        public tResultGral ResultadoFuncion
        {
            get
            {
                return this.resultadoFuncionField;
            }
            set
            {
                this.resultadoFuncionField = value;
            }
        }
        
        /// <remarks/>
        public tResultado[] Resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tParamBuscarResultados
    {
        
        private tEntidad entidadField;
        
        /// <remarks/>
        public tEntidad Entidad
        {
            get
            {
                return this.entidadField;
            }
            set
            {
                this.entidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tIngresoManual
    {
        
        private int codigoField;
        
        private string nombreField;
        
        private int longitudField;
        
        private string tipoField;
        
        /// <remarks/>
        public int Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public int Longitud
        {
            get
            {
                return this.longitudField;
            }
            set
            {
                this.longitudField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tEmpresa
    {
        
        private int codigoField;
        
        private string nombreField;
        
        private double maximoField;
        
        private bool parcialField;
        
        private bool sinFacturaField;
        
        private tIngresoManual[] ingresoManualField;
        
        private int rubroField;
        
        private int ordenField;
        
        private string nombreAdcField;
        
        private string ayudaField;
        
        /// <remarks/>
        public int Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public double Maximo
        {
            get
            {
                return this.maximoField;
            }
            set
            {
                this.maximoField = value;
            }
        }
        
        /// <remarks/>
        public bool Parcial
        {
            get
            {
                return this.parcialField;
            }
            set
            {
                this.parcialField = value;
            }
        }
        
        /// <remarks/>
        public bool SinFactura
        {
            get
            {
                return this.sinFacturaField;
            }
            set
            {
                this.sinFacturaField = value;
            }
        }
        
        /// <remarks/>
        public tIngresoManual[] IngresoManual
        {
            get
            {
                return this.ingresoManualField;
            }
            set
            {
                this.ingresoManualField = value;
            }
        }
        
        /// <remarks/>
        public int Rubro
        {
            get
            {
                return this.rubroField;
            }
            set
            {
                this.rubroField = value;
            }
        }
        
        /// <remarks/>
        public int orden
        {
            get
            {
                return this.ordenField;
            }
            set
            {
                this.ordenField = value;
            }
        }
        
        /// <remarks/>
        public string NombreAdc
        {
            get
            {
                return this.nombreAdcField;
            }
            set
            {
                this.nombreAdcField = value;
            }
        }
        
        /// <remarks/>
        public string Ayuda
        {
            get
            {
                return this.ayudaField;
            }
            set
            {
                this.ayudaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:pwsCobranzaGlobalIntf")]
    public partial class tSalidaBuscarEmpresas
    {
        
        private tResultGral resultadoFuncionField;
        
        private tEmpresa[] empresasField;
        
        /// <remarks/>
        public tResultGral ResultadoFuncion
        {
            get
            {
                return this.resultadoFuncionField;
            }
            set
            {
                this.resultadoFuncionField = value;
            }
        }
        
        /// <remarks/>
        public tEmpresa[] Empresas
        {
            get
            {
                return this.empresasField;
            }
            set
            {
                this.empresasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarEmpresas", WrapperNamespace="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal", IsWrapped=true)]
    public partial class BuscarEmpresasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ServiceCE.tParamBuscarEmpresas Param;
        
        public BuscarEmpresasRequest()
        {
        }
        
        public BuscarEmpresasRequest(ServiceCE.tParamBuscarEmpresas Param)
        {
            this.Param = Param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarEmpresasResponse", WrapperNamespace="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal", IsWrapped=true)]
    public partial class BuscarEmpresasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ServiceCE.tSalidaBuscarEmpresas @return;
        
        public BuscarEmpresasResponse()
        {
        }
        
        public BuscarEmpresasResponse(ServiceCE.tSalidaBuscarEmpresas @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarResultados", WrapperNamespace="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal", IsWrapped=true)]
    public partial class BuscarResultadosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ServiceCE.tParamBuscarResultados Param;
        
        public BuscarResultadosRequest()
        {
        }
        
        public BuscarResultadosRequest(ServiceCE.tParamBuscarResultados Param)
        {
            this.Param = Param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarResultadosResponse", WrapperNamespace="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal", IsWrapped=true)]
    public partial class BuscarResultadosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ServiceCE.tSalidaBuscarResultados @return;
        
        public BuscarResultadosResponse()
        {
        }
        
        public BuscarResultadosResponse(ServiceCE.tSalidaBuscarResultados @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarDatos", WrapperNamespace="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal", IsWrapped=true)]
    public partial class ValidarDatosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ServiceCE.tParamValidarDatos Param;
        
        public ValidarDatosRequest()
        {
        }
        
        public ValidarDatosRequest(ServiceCE.tParamValidarDatos Param)
        {
            this.Param = Param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarDatosResponse", WrapperNamespace="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal", IsWrapped=true)]
    public partial class ValidarDatosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ServiceCE.tSalidaValidarDatos @return;
        
        public ValidarDatosResponse()
        {
        }
        
        public ValidarDatosResponse(ServiceCE.tSalidaValidarDatos @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarRubros", WrapperNamespace="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal", IsWrapped=true)]
    public partial class BuscarRubrosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ServiceCE.tParamBuscarRubros Param;
        
        public BuscarRubrosRequest()
        {
        }
        
        public BuscarRubrosRequest(ServiceCE.tParamBuscarRubros Param)
        {
            this.Param = Param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarRubrosResponse", WrapperNamespace="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal", IsWrapped=true)]
    public partial class BuscarRubrosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ServiceCE.tSalidaBuscarRubros @return;
        
        public BuscarRubrosResponse()
        {
        }
        
        public BuscarRubrosResponse(ServiceCE.tSalidaBuscarRubros @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Monitor", WrapperNamespace="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal", IsWrapped=true)]
    public partial class MonitorRequest
    {
        
        public MonitorRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MonitorResponse", WrapperNamespace="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal", IsWrapped=true)]
    public partial class MonitorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public MonitorResponse()
        {
        }
        
        public MonitorResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Anulacion", WrapperNamespace="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal", IsWrapped=true)]
    public partial class AnulacionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ServiceCE.tParamAnulacion Param;
        
        public AnulacionRequest()
        {
        }
        
        public AnulacionRequest(ServiceCE.tParamAnulacion Param)
        {
            this.Param = Param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AnulacionResponse", WrapperNamespace="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal", IsWrapped=true)]
    public partial class AnulacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ServiceCE.tSalidaAnulacion @return;
        
        public AnulacionResponse()
        {
        }
        
        public AnulacionResponse(ServiceCE.tSalidaAnulacion @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AnulacionTimeOut", WrapperNamespace="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal", IsWrapped=true)]
    public partial class AnulacionTimeOutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ServiceCE.tParamAnulacionTimeOut Param;
        
        public AnulacionTimeOutRequest()
        {
        }
        
        public AnulacionTimeOutRequest(ServiceCE.tParamAnulacionTimeOut Param)
        {
            this.Param = Param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AnulacionTimeOutResponse", WrapperNamespace="urn:pwsCobranzaGlobalIntf-IpwsCobranzaGlobal", IsWrapped=true)]
    public partial class AnulacionTimeOutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ServiceCE.tSalidaAnulacion @return;
        
        public AnulacionTimeOutResponse()
        {
        }
        
        public AnulacionTimeOutResponse(ServiceCE.tSalidaAnulacion @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface IpwsCobranzaGlobalChannel : ServiceCE.IpwsCobranzaGlobal, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class IpwsCobranzaGlobalClient : System.ServiceModel.ClientBase<ServiceCE.IpwsCobranzaGlobal>, ServiceCE.IpwsCobranzaGlobal
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IpwsCobranzaGlobalClient() : 
                base(IpwsCobranzaGlobalClient.GetDefaultBinding(), IpwsCobranzaGlobalClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IpwsCobranzaGlobalPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IpwsCobranzaGlobalClient(EndpointConfiguration endpointConfiguration) : 
                base(IpwsCobranzaGlobalClient.GetBindingForEndpoint(endpointConfiguration), IpwsCobranzaGlobalClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IpwsCobranzaGlobalClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IpwsCobranzaGlobalClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IpwsCobranzaGlobalClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IpwsCobranzaGlobalClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IpwsCobranzaGlobalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceCE.BuscarEmpresasResponse BuscarEmpresas(ServiceCE.BuscarEmpresasRequest request)
        {
            return base.Channel.BuscarEmpresas(request);
        }
        
        public System.Threading.Tasks.Task<ServiceCE.BuscarEmpresasResponse> BuscarEmpresasAsync(ServiceCE.BuscarEmpresasRequest request)
        {
            return base.Channel.BuscarEmpresasAsync(request);
        }
        
        public ServiceCE.BuscarResultadosResponse BuscarResultados(ServiceCE.BuscarResultadosRequest request)
        {
            return base.Channel.BuscarResultados(request);
        }
        
        public System.Threading.Tasks.Task<ServiceCE.BuscarResultadosResponse> BuscarResultadosAsync(ServiceCE.BuscarResultadosRequest request)
        {
            return base.Channel.BuscarResultadosAsync(request);
        }
        
        public ServiceCE.ValidarDatosResponse ValidarDatos(ServiceCE.ValidarDatosRequest request)
        {
            return base.Channel.ValidarDatos(request);
        }
        
        public System.Threading.Tasks.Task<ServiceCE.ValidarDatosResponse> ValidarDatosAsync(ServiceCE.ValidarDatosRequest request)
        {
            return base.Channel.ValidarDatosAsync(request);
        }
        
        public ServiceCE.BuscarRubrosResponse BuscarRubros(ServiceCE.BuscarRubrosRequest request)
        {
            return base.Channel.BuscarRubros(request);
        }
        
        public System.Threading.Tasks.Task<ServiceCE.BuscarRubrosResponse> BuscarRubrosAsync(ServiceCE.BuscarRubrosRequest request)
        {
            return base.Channel.BuscarRubrosAsync(request);
        }
        
        public ServiceCE.MonitorResponse Monitor(ServiceCE.MonitorRequest request)
        {
            return base.Channel.Monitor(request);
        }
        
        public System.Threading.Tasks.Task<ServiceCE.MonitorResponse> MonitorAsync(ServiceCE.MonitorRequest request)
        {
            return base.Channel.MonitorAsync(request);
        }
        
        public ServiceCE.AnulacionResponse Anulacion(ServiceCE.AnulacionRequest request)
        {
            return base.Channel.Anulacion(request);
        }
        
        public System.Threading.Tasks.Task<ServiceCE.AnulacionResponse> AnulacionAsync(ServiceCE.AnulacionRequest request)
        {
            return base.Channel.AnulacionAsync(request);
        }
        
        public ServiceCE.AnulacionTimeOutResponse AnulacionTimeOut(ServiceCE.AnulacionTimeOutRequest request)
        {
            return base.Channel.AnulacionTimeOut(request);
        }
        
        public System.Threading.Tasks.Task<ServiceCE.AnulacionTimeOutResponse> AnulacionTimeOutAsync(ServiceCE.AnulacionTimeOutRequest request)
        {
            return base.Channel.AnulacionTimeOutAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IpwsCobranzaGlobalPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IpwsCobranzaGlobalPort))
            {
                return new System.ServiceModel.EndpointAddress("http://servicios12.cobroexpress.com.ar/pwsCobranzaGlobalTest.dll/soap/IpwsCobranz" +
                        "aGlobal");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IpwsCobranzaGlobalClient.GetBindingForEndpoint(EndpointConfiguration.IpwsCobranzaGlobalPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IpwsCobranzaGlobalClient.GetEndpointAddress(EndpointConfiguration.IpwsCobranzaGlobalPort);
        }
        
        public enum EndpointConfiguration
        {
            
            IpwsCobranzaGlobalPort,
        }
    }
}
